export const aligments = [
  {
    name: 'Legal Bueno',
    value: 'Legal Bueno',
    description:
      'Un personaje legal bueno combina el honor y la compasión por los inocentes. Este tipo de personajes apoya fervientemente la sociedad y sus leyes, en el convencimiento de que han sido creadas por el bien de todos. El personaje legal bueno es honesto y benevolente. Actuará dentro del sistema para intentar mejorarlo y se esfuerzan por llevar el orden allí a donde van. Combinan su compromiso a combatir el mal con una férrea disciplina, viviendo según un estricto código de honor o según las reglas marcadas por la deidad del Bien a la que sirven. Estos personajes llegarán a actuar con desprecio total de su propia vida por seguir estos códigos. En cualquier caso hay que tener en cuenta que la obediencia ciega a las leyes no es un atributo obligado para los personajes legales buenos. Por ejemplo, un paladín no infringe su alineamiento si decide tomar las armas contra un usurpador en nombre del rey destronado al que sirve, incluso si ello atenta contra las normas sobre sedición que pueda haber establecido el usurpador. Es decir, en general el personaje legal bueno prefiere una vida estructurada según un compendio de reglas que pueda seguir. Son ejemplos de personajes legales buenos el policía incorruptible, el político o gobernante (evidentemente teórico e idealizado) que actúa a favor de su gente o el soldado que actúa de forma heroica obedeciendo de forma estricta las reglas de batalla. En la literatura podemos encontrar diversos ejemplos como el caballero Sturm Brightblade (Dragonlance)',
  },
  {
    name: 'Neutral Bueno',
    value: 'Neutral Bueno',
    description:
      'Los personajes bajo este alineamiento son buenas personas a las que les gusta ayudar a los demás, pero no tienen especial predilección o rechazo por el orden. Un personaje neutral bueno no se siente particularmente obligado a hacer el bien debido a leyes o restricciones, sino que realizar el bien por sí mismo. Generalmente se plegará a la ley, pero no dudará en quebrantarla si con ello considera que está haciendo un bien mayor. No se siente atado a ningún sistema u orden social, y su necesidad de ayudar a los demás puede ser más fuerte que cualquier otra consideración. Los personajes neutrales buenos generalmente son aquellos que actúan de forma desprendida, como los miembros de la Cruz Roja o los miembros de Médicos sin Fronteras, que hacen el bien sin considerar cuál es el bando de aquellas personas a las que asisten. En la literatura de fantasía podemos considerar que Gandalf (El Señor de los Anillos) es neutral bueno: no duda en saltarse las leyes para hacer el bien, y no se siente obligado por constricciones legales o morales. En la serie Dragonlance podríamos poner como ejemplo a Tanis Semielfo. O en Harry Potter pondríamos a Dumbledore en esta posición, ya que hace el bien, aunque para ello tenga que saltarse algunas reglas o ponerse gente en contra.',
  },
  {
    name: 'Caótico Bueno',
    value: 'Caótico Bueno',
    description:
      'Un personaje caótico bueno actúa según los dictados de su conciencia sin tener en cuenta lo que los demás puedan pensar de él. Es generoso y benevolente, combinando un buen corazón con un espíritu libre. Es muy individualista y reniega de leyes, regulaciones o de cualquier orden social. Odia a la gente que se dedica a intimidar y a practicar el despotismo con los demás. Sus acciones suelen ir encaminadas a luchar contra gobernantes y organizaciones injustas, intentando liberar a los oprimidos. Evitan en la medida de lo posible sociedades organizadas, lo que les lleva en muchos casos a llevar vidas de nómadas o eremitas. Este perfil encaja con líderes rebeldes de la nobleza en lucha contra regímenes corruptos, mercenarios que solo trabajan para gente con buenos fines y, en general, todo aquel «que robe al rico para entregárselo al pobre». Robin Hood, El Zorro, el Equipo-A, Drizzt Do Urden, Tasslehoff Burrfoot (Dragonlance) o Edward Newgate (One piece) son ejemplos típicos de personajes caóticos buenos.',
  },
  {
    name: 'Legal Neutral',
    value: 'Legal Neutral',
    description:
      'Un personaje legal neutral se basa en el imperio de la ley, la tradición o el código personal. El orden, en contraposición al caos, es su brújula moral. Normalmente viven según sus códigos personales o bien apoyan gobiernos fuertes y organizados que imponen una fuerte visión de orden para todos sus súbditos. Este alineamiento combina fiabilidad y honor sin decantarse por ningún aspecto moral. Esto no quiere decir que un personaje legal neutral sea inmoral o amoral, pero los aspectos morales del mundo (el Bien y el Mal) adquieren un papel secundario frente al código, la tradición y los dictados de la lógica. Los personajes legales neutrales suelen ser funcionarios, soldados que obedecen ciegamente sus órdenes o jueces que se ciñen rígidamente a las reglas establecidas. Un buen ejemplo de personaje legal neutral es Gill Grissom, de la serie de televisión CSI: Las Vegas. Para Grissom lo importante son las pruebas, sin importar que incriminen o exculpen al sospechoso. Otro buen ejemplo es R. Daneel Olivaw, de la saga Fundación de Isaac Asimov, para quien el bienestar de la Humanidad se podía conseguir a través del orden. Por último, Javert, de Los miserables de Victor Hugo también se encuadra dentro del paradigma legal neutral.',
  },
  {
    name: 'Neutral',
    value: 'Neutral',
    description:
      'El alineamiento neutral (tanto en el aspecto ético como en el moral) carece de prejuicios o compulsiones hacia cualquier extremo de la balanza. Un personaje bajo este alineamiento hará en cada momento lo que considere más apropiado sin preferencias por el Bien o el Mal, o por el Orden y el Caos, por lo que se le hará difícil tomar una decisión estable. En general considerará que el Bien es mejor que el Mal, por puro pragmatismo, pero eso no hará que propugne el Bien considerándolo en abstracto, o de forma universal. Este es el alineamiento natural de la mayoría de los seres sensibles, como el ser humano. Los animales y criaturas de escasa inteligencia también tienen este alineamiento de forma natural. Es difícil (por no decir imposible) encontrar personajes en la literatura de Fantasía que se ciñan a este alineamiento. Un neutral sería alguien conformista que viviría tranquilo su vida sin problemas sin necesidad a salir y tener una aventura. Un ejemplo de este alineamiento es Shadow the Hedgehog de la saga de Sonic the Hedgehog.',
  },
  {
    name: 'Caótico Neutral',
    value: 'Caótico Neutral',
    description:
      'Un personaje caótico neutral se considera libre de las restricciones de la sociedad y no se ve impelido a practicar el Bien en sí. Para él, el Bien o el Mal no le interesa mucho. Los personajes caóticos neutrales siguen sus impulsos y son fuertemente individualistas. Valoran la propia libertad por encima de todo, pero no se esforzarán por conseguir la libertad de otros. Evitan la autoridad, odian las restricciones y desafían la tradición. A pesar de esto, este tipo de personajes no actúa de forma activa, al menos intencionadamente, para trastornar organizaciones de forma anárquica, ya que para ello tendría que tener algún tipo de motivación moral: el Bien para liberar a otros o el Mal para hacer sufrir a otros. El personaje caótico neutral suele ser impredecible en su comportamiento con respecto al resto de la gente, aunque es seguro que preservará su propia vida. Un contrabandista que realice pequeños robos y alquile sus servicios es el ejemplo perfecto de este alineamiento. Han Solo (antes de unirse a la Alianza Rebelde, en Star Wars) o el asesino Hugh "La Mano" es un buen ejemplo. Así mismo el clan SAO es otro buen ejemplo.',
  },
  {
    name: 'Legal Malvado',
    value: 'Legal Malvado',
    description:
      'El personaje legal malvado es devoto de forma intencionada y metódica de los sistemas despóticos, organizados y crueles. Suelen tomar todo aquello que desean con los límites marcados por su código de conducta personal, sin que les importe a quién puedan dañar en el proceso. Les importa la tradición, la lealtad y el orden, pero no les importa la libertad, la dignidad o la vida. Juega con las reglas establecidas, pero no tiene piedad o compasión. Se siente a gusto en una jerarquía fuertemente establecida, deseando ascender en ella para gobernar, nunca para obedecer. No les gusta romper su palabra, por lo que suelen ser muy cautos a la hora de empeñar su palabra, cosa que solo harán si perciben un claro beneficio a su favor. Esta reluctancia a empeñar la palabra tiene un doble origen: por un lado se debe a su naturaleza, y por otro lado se debe a su dependencia del orden establecido para protegerse de aquellos que se oponen a él en el terreno de lo moral. Algunos personajes con este alineamiento presentan tabúes como no matar ellos mismos a sangre fría, aunque pueden valerse de sicarios para hacerlo, o no dejar que los niños se metan en problemas, si pueden evitarlo. Normalmente consideran que estos preceptos morales los sitúan por encima del resto de villanos. En ocasiones los personajes legales malvados pueden dedicarse celosamente a la causa del Mal con el mismo celo que un paladín se dedica a la causa del Bien. Más allá de su inclinación natural a causar daño para conseguir sus propios objetivos, se complacen en el Mal como fin en sí mismo. También suelen causar el Mal como parte de los objetivos de una deidad o maestro. Los personajes legales malvados suelen considerarse diabólicos puesto que los diablos son la personificación de este alineamiento. Un tirano que redacta leyes para su conveniencia, un abogado corrupto, un juez que utiliza la ley para enmascarar sus actos reprobables o miembros despiadados del crimen organizado son buenas muestras de este alineamiento. En la literatura tenemos ejemplos como Randall Flagg, personaje de la novela Apocalipsis de Stephen King. Los caballeros de la Orden de Takhisis en la saga Dragonlance son también un buen ejemplo de personajes legales malvados. Por no hablar del dios (anteriormente Archidiablo) Asmodeo.',
  },
  {
    name: 'Neutral Malvado',
    value: 'Neutral Malvado',
    description:
      'El personaje neutral malvado es puro pragmatismo sin honor y sin variaciones en su brújula moral. Se ciñe a la máxima «supervivencia de los más dotados». Este tipo de personajes siempre harán lo que sea para salir impunes. Solo se preocupan por sí mismos. No les tiembla el pulso a la hora de matar, ya sea por beneficio, deporte o conveniencia. No siente inclinación por el orden y no respeta las leyes, tradiciones o códigos que lo harían más noble en algún sentido. Por otro lado no se sienten particularmente inclinados hacia el conflicto o la guerra. Algunos personajes neutrales malvados tienen el Mal como ideal, realizando actos malvados para extender el Mal, como fin en sí mismo. Normalmente suelen pertenecer a sociedades o deidades del Mal. Un personaje neutral malvado es el Mal en estado puro, un criminal sin honor y más allá de toda redención. Saruman, en El Señor de los Anillos, es un buen ejemplo de personaje neutral malvado.',
  },
  {
    name: 'Caótico Malvado',
    value: 'Caótico Malvado',
    description:
      'El personaje caótico malvado representa el poder sin control, el egoísmo absoluto sin cadenas, totalmente al margen de la ley. Este tipo de personajes solo se guían por sus ansias de poder, odio y sed de destrucción. Es violento, cruel, agresivo, impredecible, despiadado y brutal. Por fortuna sus planes son muy desordenados, y todo grupo al que se una estará pobremente organizado. Normalmente colaboran solo a través de la fuerza, y como líderes se mantienen en la cúspide únicamente mientras no sean asesinados. Los demonios son el paradigma de seres caóticos malvados. Los asesinos en serie, por ejemplo, son personajes caóticos malvados. En la literatura podemos considerar a Melkor, antagonista principal del libro El Silmarillion, de J. R. R. Tolkien, como ejemplo perfecto de ser caótico malvado o Joker de Batman ya que su único fin es crear destrucción y desolación sin importarle el dinero o el poder que como buscan otros villanos.',
  },
]

export default aligments
